# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PicketFence.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(822, 882)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cmap4 = QtWidgets.QComboBox(Form)
        self.cmap4.setObjectName("cmap4")
        self.cmap4.addItem("")
        self.cmap4.addItem("")
        self.cmap4.addItem("")
        self.cmap4.addItem("")
        self.cmap4.addItem("")
        self.cmap4.addItem("")
        self.cmap4.addItem("")
        self.verticalLayout.addWidget(self.cmap4)
        self.PF4 = MatplotlibWidget(Form)
        self.PF4.setObjectName("PF4")
        self.verticalLayout.addWidget(self.PF4)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cmap1 = QtWidgets.QComboBox(Form)
        self.cmap1.setObjectName("cmap1")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.verticalLayout_2.addWidget(self.cmap1)
        self.PF1 = MatplotlibWidget(Form)
        self.PF1.setObjectName("PF1")
        self.verticalLayout_2.addWidget(self.PF1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cmap2 = QtWidgets.QComboBox(Form)
        self.cmap2.setObjectName("cmap2")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.verticalLayout_3.addWidget(self.cmap2)
        self.PF2 = MatplotlibWidget(Form)
        self.PF2.setObjectName("PF2")
        self.verticalLayout_3.addWidget(self.PF2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cmap3 = QtWidgets.QComboBox(Form)
        self.cmap3.setObjectName("cmap3")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.verticalLayout_4.addWidget(self.cmap3)
        self.PF3 = MatplotlibWidget(Form)
        self.PF3.setObjectName("PF3")
        self.verticalLayout_4.addWidget(self.PF3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.ResultsLabel = QtWidgets.QLabel(Form)
        self.ResultsLabel.setObjectName("ResultsLabel")
        self.gridLayout_2.addWidget(self.ResultsLabel, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PicketFence"))
        self.cmap4.setItemText(0, _translate("Form", "gray"))
        self.cmap4.setItemText(1, _translate("Form", "prism"))
        self.cmap4.setItemText(2, _translate("Form", "autumn"))
        self.cmap4.setItemText(3, _translate("Form", "cool"))
        self.cmap4.setItemText(4, _translate("Form", "spring"))
        self.cmap4.setItemText(5, _translate("Form", "summer"))
        self.cmap4.setItemText(6, _translate("Form", "winter"))
        self.cmap1.setItemText(0, _translate("Form", "gray"))
        self.cmap1.setItemText(1, _translate("Form", "prism"))
        self.cmap1.setItemText(2, _translate("Form", "autumn"))
        self.cmap1.setItemText(3, _translate("Form", "cool"))
        self.cmap1.setItemText(4, _translate("Form", "spring"))
        self.cmap1.setItemText(5, _translate("Form", "summer"))
        self.cmap1.setItemText(6, _translate("Form", "winter"))
        self.cmap2.setItemText(0, _translate("Form", "gray"))
        self.cmap2.setItemText(1, _translate("Form", "prism"))
        self.cmap2.setItemText(2, _translate("Form", "autumn"))
        self.cmap2.setItemText(3, _translate("Form", "cool"))
        self.cmap2.setItemText(4, _translate("Form", "spring"))
        self.cmap2.setItemText(5, _translate("Form", "summer"))
        self.cmap2.setItemText(6, _translate("Form", "winter"))
        self.cmap3.setItemText(0, _translate("Form", "gray"))
        self.cmap3.setItemText(1, _translate("Form", "prism"))
        self.cmap3.setItemText(2, _translate("Form", "autumn"))
        self.cmap3.setItemText(3, _translate("Form", "cool"))
        self.cmap3.setItemText(4, _translate("Form", "spring"))
        self.cmap3.setItemText(5, _translate("Form", "summer"))
        self.cmap3.setItemText(6, _translate("Form", "winter"))
        self.ResultsLabel.setText(_translate("Form", "Results:"))

from matplotlibwidget import MatplotlibWidget
