# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SSS.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1048, 869)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cmapCombi = QtWidgets.QComboBox(Form)
        self.cmapCombi.setObjectName("cmapCombi")
        self.cmapCombi.addItem("")
        self.cmapCombi.addItem("")
        self.cmapCombi.addItem("")
        self.cmapCombi.addItem("")
        self.cmapCombi.addItem("")
        self.cmapCombi.addItem("")
        self.cmapCombi.addItem("")
        self.verticalLayout_5.addWidget(self.cmapCombi)
        self.SSSCombi = MatplotlibWidget(Form)
        self.SSSCombi.setObjectName("SSSCombi")
        self.verticalLayout_5.addWidget(self.SSSCombi)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cmap1 = QtWidgets.QComboBox(Form)
        self.cmap1.setObjectName("cmap1")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.verticalLayout.addWidget(self.cmap1)
        self.SSS1 = MatplotlibWidget(Form)
        self.SSS1.setObjectName("SSS1")
        self.verticalLayout.addWidget(self.SSS1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cmap2 = QtWidgets.QComboBox(Form)
        self.cmap2.setObjectName("cmap2")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.verticalLayout_2.addWidget(self.cmap2)
        self.SSS2 = MatplotlibWidget(Form)
        self.SSS2.setObjectName("SSS2")
        self.verticalLayout_2.addWidget(self.SSS2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cmap3 = QtWidgets.QComboBox(Form)
        self.cmap3.setObjectName("cmap3")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.verticalLayout_3.addWidget(self.cmap3)
        self.SSS3 = MatplotlibWidget(Form)
        self.SSS3.setObjectName("SSS3")
        self.verticalLayout_3.addWidget(self.SSS3)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cmap4 = QtWidgets.QComboBox(Form)
        self.cmap4.setObjectName("cmap4")
        self.cmap4.addItem("")
        self.cmap4.addItem("")
        self.cmap4.addItem("")
        self.cmap4.addItem("")
        self.cmap4.addItem("")
        self.cmap4.addItem("")
        self.cmap4.addItem("")
        self.verticalLayout_4.addWidget(self.cmap4)
        self.SSS4 = MatplotlibWidget(Form)
        self.SSS4.setObjectName("SSS4")
        self.verticalLayout_4.addWidget(self.SSS4)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.SSS3.raise_()
        self.SSS4.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Synchronised Segment Stripes"))
        self.cmapCombi.setItemText(0, _translate("Form", "gray"))
        self.cmapCombi.setItemText(1, _translate("Form", "prism"))
        self.cmapCombi.setItemText(2, _translate("Form", "autumn"))
        self.cmapCombi.setItemText(3, _translate("Form", "cool"))
        self.cmapCombi.setItemText(4, _translate("Form", "spring"))
        self.cmapCombi.setItemText(5, _translate("Form", "summer"))
        self.cmapCombi.setItemText(6, _translate("Form", "winter"))
        self.cmap1.setItemText(0, _translate("Form", "gray"))
        self.cmap1.setItemText(1, _translate("Form", "prism"))
        self.cmap1.setItemText(2, _translate("Form", "autumn"))
        self.cmap1.setItemText(3, _translate("Form", "cool"))
        self.cmap1.setItemText(4, _translate("Form", "spring"))
        self.cmap1.setItemText(5, _translate("Form", "summer"))
        self.cmap1.setItemText(6, _translate("Form", "winter"))
        self.cmap2.setItemText(0, _translate("Form", "gray"))
        self.cmap2.setItemText(1, _translate("Form", "prism"))
        self.cmap2.setItemText(2, _translate("Form", "autumn"))
        self.cmap2.setItemText(3, _translate("Form", "cool"))
        self.cmap2.setItemText(4, _translate("Form", "spring"))
        self.cmap2.setItemText(5, _translate("Form", "summer"))
        self.cmap2.setItemText(6, _translate("Form", "winter"))
        self.cmap3.setItemText(0, _translate("Form", "gray"))
        self.cmap3.setItemText(1, _translate("Form", "prism"))
        self.cmap3.setItemText(2, _translate("Form", "autumn"))
        self.cmap3.setItemText(3, _translate("Form", "cool"))
        self.cmap3.setItemText(4, _translate("Form", "spring"))
        self.cmap3.setItemText(5, _translate("Form", "summer"))
        self.cmap3.setItemText(6, _translate("Form", "winter"))
        self.cmap4.setItemText(0, _translate("Form", "gray"))
        self.cmap4.setItemText(1, _translate("Form", "prism"))
        self.cmap4.setItemText(2, _translate("Form", "autumn"))
        self.cmap4.setItemText(3, _translate("Form", "cool"))
        self.cmap4.setItemText(4, _translate("Form", "spring"))
        self.cmap4.setItemText(5, _translate("Form", "summer"))
        self.cmap4.setItemText(6, _translate("Form", "winter"))

from matplotlibwidget import MatplotlibWidget
