# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SSSWidget.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SSS(object):
    def setupUi(self, SSS):
        SSS.setObjectName("SSS")
        SSS.resize(697, 1015)
        self.layoutWidget_4 = QtWidgets.QWidget(SSS)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 0, 691, 541))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cmapCombi = QtWidgets.QComboBox(self.layoutWidget_4)
        self.cmapCombi.setObjectName("cmapCombi")
        self.cmapCombi.addItem("")
        self.cmapCombi.addItem("")
        self.cmapCombi.addItem("")
        self.cmapCombi.addItem("")
        self.cmapCombi.addItem("")
        self.cmapCombi.addItem("")
        self.cmapCombi.addItem("")
        self.verticalLayout_5.addWidget(self.cmapCombi)
        self.SSSCombi = MatplotlibWidget(self.layoutWidget_4)
        self.SSSCombi.setObjectName("SSSCombi")
        self.verticalLayout_5.addWidget(self.SSSCombi)
        self.widget = QtWidgets.QWidget(SSS)
        self.widget.setGeometry(QtCore.QRect(0, 540, 691, 471))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cmap1 = QtWidgets.QComboBox(self.widget)
        self.cmap1.setObjectName("cmap1")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.verticalLayout.addWidget(self.cmap1)
        self.SSS1 = MatplotlibWidget(self.widget)
        self.SSS1.setObjectName("SSS1")
        self.verticalLayout.addWidget(self.SSS1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cmap2 = QtWidgets.QComboBox(self.widget)
        self.cmap2.setObjectName("cmap2")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.verticalLayout_2.addWidget(self.cmap2)
        self.SSS2 = MatplotlibWidget(self.widget)
        self.SSS2.setObjectName("SSS2")
        self.verticalLayout_2.addWidget(self.SSS2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cmap3 = QtWidgets.QComboBox(self.widget)
        self.cmap3.setObjectName("cmap3")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.verticalLayout_3.addWidget(self.cmap3)
        self.SSS3 = MatplotlibWidget(self.widget)
        self.SSS3.setObjectName("SSS3")
        self.verticalLayout_3.addWidget(self.SSS3)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cmap4 = QtWidgets.QComboBox(self.widget)
        self.cmap4.setObjectName("cmap4")
        self.cmap4.addItem("")
        self.cmap4.addItem("")
        self.cmap4.addItem("")
        self.cmap4.addItem("")
        self.cmap4.addItem("")
        self.cmap4.addItem("")
        self.cmap4.addItem("")
        self.verticalLayout_4.addWidget(self.cmap4)
        self.SSS4 = MatplotlibWidget(self.widget)
        self.SSS4.setObjectName("SSS4")
        self.verticalLayout_4.addWidget(self.SSS4)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)

        self.retranslateUi(SSS)
        QtCore.QMetaObject.connectSlotsByName(SSS)

    def retranslateUi(self, SSS):
        _translate = QtCore.QCoreApplication.translate
        SSS.setWindowTitle(_translate("SSS", "Synchronised Segment Stripes"))
        self.cmapCombi.setItemText(0, _translate("SSS", "gray"))
        self.cmapCombi.setItemText(1, _translate("SSS", "prism"))
        self.cmapCombi.setItemText(2, _translate("SSS", "autumn"))
        self.cmapCombi.setItemText(3, _translate("SSS", "cool"))
        self.cmapCombi.setItemText(4, _translate("SSS", "spring"))
        self.cmapCombi.setItemText(5, _translate("SSS", "summer"))
        self.cmapCombi.setItemText(6, _translate("SSS", "winter"))
        self.cmap1.setItemText(0, _translate("SSS", "gray"))
        self.cmap1.setItemText(1, _translate("SSS", "prism"))
        self.cmap1.setItemText(2, _translate("SSS", "autumn"))
        self.cmap1.setItemText(3, _translate("SSS", "cool"))
        self.cmap1.setItemText(4, _translate("SSS", "spring"))
        self.cmap1.setItemText(5, _translate("SSS", "summer"))
        self.cmap1.setItemText(6, _translate("SSS", "winter"))
        self.cmap2.setItemText(0, _translate("SSS", "gray"))
        self.cmap2.setItemText(1, _translate("SSS", "prism"))
        self.cmap2.setItemText(2, _translate("SSS", "autumn"))
        self.cmap2.setItemText(3, _translate("SSS", "cool"))
        self.cmap2.setItemText(4, _translate("SSS", "spring"))
        self.cmap2.setItemText(5, _translate("SSS", "summer"))
        self.cmap2.setItemText(6, _translate("SSS", "winter"))
        self.cmap3.setItemText(0, _translate("SSS", "gray"))
        self.cmap3.setItemText(1, _translate("SSS", "prism"))
        self.cmap3.setItemText(2, _translate("SSS", "autumn"))
        self.cmap3.setItemText(3, _translate("SSS", "cool"))
        self.cmap3.setItemText(4, _translate("SSS", "spring"))
        self.cmap3.setItemText(5, _translate("SSS", "summer"))
        self.cmap3.setItemText(6, _translate("SSS", "winter"))
        self.cmap4.setItemText(0, _translate("SSS", "gray"))
        self.cmap4.setItemText(1, _translate("SSS", "prism"))
        self.cmap4.setItemText(2, _translate("SSS", "autumn"))
        self.cmap4.setItemText(3, _translate("SSS", "cool"))
        self.cmap4.setItemText(4, _translate("SSS", "spring"))
        self.cmap4.setItemText(5, _translate("SSS", "summer"))
        self.cmap4.setItemText(6, _translate("SSS", "winter"))

from matplotlibwidget import MatplotlibWidget
