# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Wedges.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1022, 962)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CombiLayout = QtWidgets.QVBoxLayout()
        self.CombiLayout.setObjectName("CombiLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_cmap3 = QtWidgets.QComboBox(Form)
        self.comboBox_cmap3.setObjectName("comboBox_cmap3")
        self.comboBox_cmap3.addItem("")
        self.comboBox_cmap3.addItem("")
        self.comboBox_cmap3.addItem("")
        self.comboBox_cmap3.addItem("")
        self.comboBox_cmap3.addItem("")
        self.comboBox_cmap3.addItem("")
        self.comboBox_cmap3.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_cmap3)
        self.CombiLayout.addLayout(self.horizontalLayout)
        self.CombinedWedges = MatplotlibWidget(Form)
        self.CombinedWedges.setObjectName("CombinedWedges")
        self.CombiLayout.addWidget(self.CombinedWedges)
        self.horizontalLayout_3.addLayout(self.CombiLayout)
        self.profiler = MatplotlibWidget(Form)
        self.profiler.setObjectName("profiler")
        self.horizontalLayout_3.addWidget(self.profiler)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Wedge1Layout = QtWidgets.QVBoxLayout()
        self.Wedge1Layout.setObjectName("Wedge1Layout")
        self.comboBox_cmap1 = QtWidgets.QComboBox(Form)
        self.comboBox_cmap1.setObjectName("comboBox_cmap1")
        self.comboBox_cmap1.addItem("")
        self.comboBox_cmap1.addItem("")
        self.comboBox_cmap1.addItem("")
        self.comboBox_cmap1.addItem("")
        self.comboBox_cmap1.addItem("")
        self.comboBox_cmap1.addItem("")
        self.comboBox_cmap1.addItem("")
        self.Wedge1Layout.addWidget(self.comboBox_cmap1)
        self.Wedge1 = MatplotlibWidget(Form)
        self.Wedge1.setObjectName("Wedge1")
        self.Wedge1Layout.addWidget(self.Wedge1)
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.Wedge1Layout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.Wedge1Layout)
        self.Wedge2Layout = QtWidgets.QVBoxLayout()
        self.Wedge2Layout.setObjectName("Wedge2Layout")
        self.comboBox_cmap2 = QtWidgets.QComboBox(Form)
        self.comboBox_cmap2.setObjectName("comboBox_cmap2")
        self.comboBox_cmap2.addItem("")
        self.comboBox_cmap2.addItem("")
        self.comboBox_cmap2.addItem("")
        self.comboBox_cmap2.addItem("")
        self.comboBox_cmap2.addItem("")
        self.comboBox_cmap2.addItem("")
        self.comboBox_cmap2.addItem("")
        self.Wedge2Layout.addWidget(self.comboBox_cmap2)
        self.Wedge2 = MatplotlibWidget(Form)
        self.Wedge2.setObjectName("Wedge2")
        self.Wedge2Layout.addWidget(self.Wedge2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.Wedge2Layout.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.Wedge2Layout)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Wedges"))
        self.comboBox_cmap3.setItemText(0, _translate("Form", "gray"))
        self.comboBox_cmap3.setItemText(1, _translate("Form", "prism"))
        self.comboBox_cmap3.setItemText(2, _translate("Form", "autumn"))
        self.comboBox_cmap3.setItemText(3, _translate("Form", "cool"))
        self.comboBox_cmap3.setItemText(4, _translate("Form", "spring"))
        self.comboBox_cmap3.setItemText(5, _translate("Form", "summer"))
        self.comboBox_cmap3.setItemText(6, _translate("Form", "winter"))
        self.comboBox_cmap1.setItemText(0, _translate("Form", "gray"))
        self.comboBox_cmap1.setItemText(1, _translate("Form", "prism"))
        self.comboBox_cmap1.setItemText(2, _translate("Form", "autumn"))
        self.comboBox_cmap1.setItemText(3, _translate("Form", "cool"))
        self.comboBox_cmap1.setItemText(4, _translate("Form", "spring"))
        self.comboBox_cmap1.setItemText(5, _translate("Form", "summer"))
        self.comboBox_cmap1.setItemText(6, _translate("Form", "winter"))
        self.comboBox_cmap2.setItemText(0, _translate("Form", "gray"))
        self.comboBox_cmap2.setItemText(1, _translate("Form", "prism"))
        self.comboBox_cmap2.setItemText(2, _translate("Form", "autumn"))
        self.comboBox_cmap2.setItemText(3, _translate("Form", "cool"))
        self.comboBox_cmap2.setItemText(4, _translate("Form", "spring"))
        self.comboBox_cmap2.setItemText(5, _translate("Form", "summer"))
        self.comboBox_cmap2.setItemText(6, _translate("Form", "winter"))

from matplotlibwidget import MatplotlibWidget
